openapi: 3.1.0
info:
  title: ElevenLabs TTS Proxy
  version: 1.1.0
servers:
  - url: 
https://dino-tts-proxy-4hu5.vercel.app
components:
  securitySchemes:
    proxyKey:
      type: apiKey
      in: header
      name: Miguel
  schemas: {}
paths:
  /tts:
    post:
      operationId: tts_elevenlabs
      security:
        - proxyKey: []
      summary: Convierte texto en audio (mp3)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text: { type: string, maxLength: 1200 }
                voice_id: { type: string }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  audio_base64: { type: string }
                  data_url: { type: string }
                  mime: { type: string, example: audio/mpeg }


